# Generated by Django 5.0.2 on 2024-03-03 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libros', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='favorite',
            name='book',
        ),
        migrations.RemoveField(
            model_name='user_like',
            name='like',
        ),
        migrations.AddField(
            model_name='favorite',
            name='book',
            field=models.ManyToManyField(to='libros.book'),
        ),
        migrations.AddField(
            model_name='user_like',
            name='like',
            field=models.ManyToManyField(to='libros.genders'),
        ),
    ]
