# Generated by Django 5.0.2 on 2024-03-04 01:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('libros', '0002_remove_favorite_book_remove_user_like_like_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='author',
            old_name='author_namev',
            new_name='author_name',
        ),
        migrations.RenameField(
            model_name='genders',
            old_name='genders',
            new_name='gender',
        ),
        migrations.RenameField(
            model_name='publisher',
            old_name='pubisher',
            new_name='publisher',
        ),
    ]
