# Generated by Django 5.0.2 on 2024-03-17 05:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libros', '0003_rename_author_namev_author_author_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('publich_date', models.DateTimeField(auto_now_add=True)),
                ('rating', models.BooleanField(default=True)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='libros.book')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='libros.user')),
            ],
            options={
                'unique_together': {('user', 'book')},
            },
        ),
    ]
