# Generated by Django 5.0.2 on 2024-04-07 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libros', '0006_book_date_publishir'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_like',
            name='like',
        ),
        migrations.RemoveField(
            model_name='user_like',
            name='user',
        ),
        migrations.AddField(
            model_name='user',
            name='favorite_genres',
            field=models.ManyToManyField(to='libros.genders'),
        ),
        migrations.AddField(
            model_name='user',
            name='liked_books',
            field=models.ManyToManyField(to='libros.book'),
        ),
        migrations.RemoveField(
            model_name='book',
            name='author',
        ),
        migrations.AlterField(
            model_name='book',
            name='date_publishir',
            field=models.DateField(blank=True),
        ),
        migrations.RemoveField(
            model_name='book',
            name='genders',
        ),
        migrations.RemoveField(
            model_name='book',
            name='language',
        ),
        migrations.DeleteModel(
            name='Favorite',
        ),
        migrations.DeleteModel(
            name='User_like',
        ),
        migrations.AddField(
            model_name='book',
            name='author',
            field=models.ManyToManyField(to='libros.author'),
        ),
        migrations.AddField(
            model_name='book',
            name='genders',
            field=models.ManyToManyField(to='libros.genders'),
        ),
        migrations.AddField(
            model_name='book',
            name='language',
            field=models.ManyToManyField(to='libros.language'),
        ),
    ]
