# Generated by Django 5.0.2 on 2024-04-21 05:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('libros', '0008_bookitem'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BookItem',
        ),
    ]
