# Generated by Django 5.0.2 on 2024-05-19 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libros', '0009_delete_bookitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='pic',
            field=models.ImageField(blank=True, null=True, upload_to='author_images/'),
        ),
        migrations.AddField(
            model_name='book',
            name='port',
            field=models.ImageField(blank=True, null=True, upload_to='book_images/'),
        ),
        migrations.AddField(
            model_name='genders',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='genres_images/'),
        ),
    ]
